/* DO NOT EDIT THIS FILE - it is machine generated */

/* Header for class com_example_mbenben_studydemo_basenote_tetsjni_JniKit */

#ifndef _Included_com_example_mbenben_studydemo_basenote_tetsjni_JniKit
#define _Included_com_example_mbenben_studydemo_basenote_tetsjni_JniKit
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_mbenben_studydemo_basenote_tetsjni_JniKit
 * Method:    myFirstC
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_mbenben_studydemo_basenote_tetsjni_JniKit_myFirstC
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
