package com.example.mbenben.studydemo.greendao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.example.mbenben.studydemo.greendao.entity.ContentProviderInfo;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "CONTENT_PROVIDER_INFO".
*/
public class ContentProviderInfoDao extends AbstractDao<ContentProviderInfo, Long> {

    public static final String TABLENAME = "CONTENT_PROVIDER_INFO";

    /**
     * Properties of entity ContentProviderInfo.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property MContent = new Property(1, String.class, "mContent", false, "M_CONTENT");
        public final static Property MName = new Property(2, String.class, "mName", false, "M_NAME");
    }


    public ContentProviderInfoDao(DaoConfig config) {
        super(config);
    }
    
    public ContentProviderInfoDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"CONTENT_PROVIDER_INFO\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"M_CONTENT\" TEXT," + // 1: mContent
                "\"M_NAME\" TEXT);"); // 2: mName
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"CONTENT_PROVIDER_INFO\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, ContentProviderInfo entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String mContent = entity.getMContent();
        if (mContent != null) {
            stmt.bindString(2, mContent);
        }
 
        String mName = entity.getMName();
        if (mName != null) {
            stmt.bindString(3, mName);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, ContentProviderInfo entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String mContent = entity.getMContent();
        if (mContent != null) {
            stmt.bindString(2, mContent);
        }
 
        String mName = entity.getMName();
        if (mName != null) {
            stmt.bindString(3, mName);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public ContentProviderInfo readEntity(Cursor cursor, int offset) {
        ContentProviderInfo entity = new ContentProviderInfo( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // mContent
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2) // mName
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, ContentProviderInfo entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setMContent(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setMName(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(ContentProviderInfo entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(ContentProviderInfo entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(ContentProviderInfo entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
