package com.example.mbenben.studydemo.greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.example.mbenben.studydemo.greendao.entity.ContentProviderInfo;

import com.example.mbenben.studydemo.greendao.ContentProviderInfoDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig contentProviderInfoDaoConfig;

    private final ContentProviderInfoDao contentProviderInfoDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        contentProviderInfoDaoConfig = daoConfigMap.get(ContentProviderInfoDao.class).clone();
        contentProviderInfoDaoConfig.initIdentityScope(type);

        contentProviderInfoDao = new ContentProviderInfoDao(contentProviderInfoDaoConfig, this);

        registerDao(ContentProviderInfo.class, contentProviderInfoDao);
    }
    
    public void clear() {
        contentProviderInfoDaoConfig.clearIdentityScope();
    }

    public ContentProviderInfoDao getContentProviderInfoDao() {
        return contentProviderInfoDao;
    }

}
